packages:
  - "apps/web/*"
  - "apps/desktop/frontend-app"
  - "apps/vscode-extension"
  - "packages/*"
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  sharp: true
  unrs-resolver: true
